### ISSUE TITLE
Error! Your kernel headers for kernel 5.9.0-arm-64 cannot be found.

### ISSUE THREAD

**Issue by LiuTianP** [brektrou/rtl8821CU#114]
Error! Your kernel headers for kernel 5.9.0-arm-64 cannot be found.

**Comment by brektrou** [comment]
Install `linux-headers` or `kernel-devel` package

**Comment by LiuTianP** [comment]
> Install `linux-headers` or `kernel-devel` package

thinks

**Comment by cyh801** [comment]
https://users.armbian.com/balbes150/arm-64/deb/
