### ISSUE TITLE
Unable to build for Linux kernel version 5.12

### ISSUE THREAD

**Issue by EFanZh** [brektrou/rtl8821CU#132]
Maybe related: https://github.com/RinCat/RTL88x2BU-Linux-Driver/issues/81.

**Comment by TheGamingCoderNoob** [comment]
I have same issue.

**Comment by tupabeep** [comment]
I have same issue.

**Comment by ylxdzsw** [comment]
The patch in  RinCat/RTL88x2BU-Linux-Driver#81 works for me. Just change the `GRO_DROP` to `GRO_MERGED_FREE` and it compiles and works

**Comment by EFanZh** [comment]
Closed by #134.
