### ISSUE TITLE
Can not work on kernel 5.3-rc5

### ISSUE THREAD

**Issue by yutent** [brektrou/rtl8821CU#15]
```
OS: Linux Mint 19.2 Tina x86_64 
```
It works on kernel 5.2.9, but not 5.3-rc5

**Comment by smp79** [comment]
Same here with current 5.3-rc8. OS: LibreELEC

**Comment by licardoY** [comment]
works on 5.1.10, but not 5.3rc8.....

**Comment by breisig** [comment]
It doesn't work on 5.3.0 final either.

**Comment by dscottboggs** [comment]
Is there any more information besides "it doesn't work"?

**Comment by breisig** [comment]
Here's some debug message on 5.3.1

[    9.578352] usb 1-1: New USB device found, idVendor=0bda, idProduct=c811, bcdDevice= 2.00
[    9.578353] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    9.578354] usb 1-1: Product: 802.11ac NIC
[    9.578355] usb 1-1: Manufacturer: Realtek
[    9.578355] usb 1-1: SerialNumber: 123456
[    9.596880] 8821cu: no symbol version for module_layout
[    9.596893] 8821cu: loading out-of-tree module taints kernel.
[    9.656145] 8821cu: module verification failed: signature and/or required key missing - tainting kernel
[    9.666426] RTW: module init start
[    9.666428] RTW: rtl8821cu v5.4.1_28754.20180921_COEX20180712-3232
[    9.666428] RTW: build time: Sep 21 2019 14:33:47
[    9.666428] RTW: rtl8821cu BT-Coex version = COEX20180712-3232
[    9.666463] RTW: [HALMAC]11692M
               HALMAC_MAJOR_VER = 1
               HALMAC_PROTOTYPE_VER = 4
               HALMAC_MINOR_VER = 19
               HALMAC_PATCH_VER = 3
[    9.670527] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[   10.402471] RTW: HW EFUSE
[   10.402472] RTW: 0x000: 29 81 00 BC  09 00 31 00  6F 04 A4 10  12 00 30 0B
[   10.402475] RTW: 0x010: 23 23 23 24  24 24 2B 2B  2B 2C 2C 02  FF FF FF FF
[   10.402477] RTW: 0x020: FF FF 2B 2A  28 28 27 27  28 28 29 29  27 29 29 29
[   10.402479] RTW: 0x030: 24 FF FF FF  FF FF D0 FF  FF FF 23 23  23 24 24 24
[   10.402481] RTW: 0x040: 2B 2B 2B 2C  2C 02 FF FF  FF FF FF FF  FF FF FF FF
[   10.402483] RTW: 0x050: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   10.402485] RTW: 0x060: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   10.402487] RTW: 0x070: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   10.402489] RTW: 0x080: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   10.402491] RTW: 0x090: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   10.402493] RTW: 0x0A0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   10.402495] RTW: 0x0B0: FF FF FF FF  FF FF FF FF  7F 06 1A 00  FF FF FF FF
[   10.402496] RTW: 0x0C0: FF 22 00 41  00 00 00 00  00 FF 22 FF  FF FF FF FF
[   10.402498] RTW: 0x0D0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   10.402500] RTW: 0x0E0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   10.402502] RTW: 0x0F0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   10.402504] RTW: 0x100: DA 0B 11 C8  C3 46 02 40  A5 EF 4E 92  81 09 03 52
[   10.402506] RTW: 0x110: 65 61 6C 74  65 6B 0E 03  38 30 32 2E  31 31 61 63
[   10.402508] RTW: 0x120: 20 4E 49 43  08 03 31 32  33 34 35 36  FF FF FF FF
[   10.402510] RTW: 0x130: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   10.402512] RTW: 0x140: FF FF FF FF  00 00 31 0F  FF FF FF FF  FF FF FF FF
[   10.402514] RTW: 0x150: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   10.402516] RTW: 0x160: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   10.402518] RTW: 0x170: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   10.402520] RTW: 0x180: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   10.402522] RTW: 0x190: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   10.402524] RTW: 0x1A0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   10.402526] RTW: 0x1B0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   10.402527] RTW: 0x1C0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   10.402529] RTW: 0x1D0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   10.402531] RTW: 0x1E0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   10.402533] RTW: 0x1F0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   10.403149] RTW: hal_com_config_channel_plan chplan:0x7F
[   10.435401] RTW: [HALMAC][ALWAYS]shall R reg twice!!
[   10.444928] RTW: WARN [HALMAC][WARN]H2C/C2H ver is compatible!!
[   10.742752] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[   10.743356] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[   10.743990] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[   10.744600] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[   10.745220] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[   10.745838] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[   10.746491] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[   10.747266] RTW: rtw_regsty_chk_target_tx_power_valid return _FALSE for band:0, path:0, rs:0, t:-1
[   10.753103] ------------[ cut here ]------------
[   10.753123] WARNING: CPU: 7 PID: 5732 at net/wireless/core.c:868 wiphy_register.cold+0x37/0x435
[   10.753123] Modules linked in: pcc_cpufreq(-) acpi_cpufreq(-) xt_multiport ip6t_rpfilter ip6t_REJECT nf_reject_ipv6 ipt_REJECT nf_reject_ipv4 xt_conntrack ebtable_nat ip6table_nat ip6table_mangle ip6table_security ip6table_raw iptable_nat nf_nat iptable_mangle iptable_security iptable_raw nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 8821cu(OE+) ebtable_filter ebtables intel_rapl_msr intel_rapl_common ip6table_filter ip6_tables iptable_filter bpfilter crct10dif_pclmul crc32_pclmul crc32c_intel snd_pcm_oss ghash_clmulni_intel snd_mixer_oss iTCO_wdt aesni_intel iTCO_vendor_support bochs_drm aes_x86_64 uhci_hcd snd_hda_intel crypto_simd drm_vram_helper snd_hda_codec cryptd ttm glue_helper snd_hda_core joydev drm_kms_helper snd_hwdep snd_pcm drm intel_agp snd_timer intel_gtt snd lpc_ich soundcore ehci_pci agpgart ehci_hcd serio_raw i2c_i801 evdev sch_fq_codel ip_tables
[   10.753139] CPU: 7 PID: 5732 Comm: modprobe Tainted: G           OE     5.3.1 #1
[   10.753140] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS rel-1.12.1-0-ga5cab58e9a3f-prebuilt.qemu.org 04/01/2014
[   10.753141] RIP: 0010:wiphy_register.cold+0x37/0x435
[   10.753142] Code: 0b b8 ea ff ff ff e9 e4 e7 ff ff 48 c7 c7 a8 91 dd 82 e8 b5 a0 be fe 0f 0b e9 ae ec ff ff 48 c7 c7 a8 91 dd 82 e8 a2 a0 be fe <0f> 0b b8 ea ff ff ff e9 b9 e7 ff ff 48 c7 c7 a8 91 dd 82 e8 8a a0
[   10.753142] RSP: 0018:ffff888273e079b0 EFLAGS: 00010246
[   10.753143] RAX: 0000000000000024 RBX: 000000000000034e RCX: 0000000000000000
[   10.753144] RDX: 0000000000000000 RSI: ffff88827fdd73d8 RDI: ffff88827fdd73d8
[   10.753144] RBP: ffff888273e07a20 R08: ffff88827fdd73d8 R09: 0000000000000001
[   10.753144] R10: 0000000000000000 R11: 0000000000000001 R12: ffff888273426300
[   10.753145] R13: 0000000000000000 R14: ffffc900000fc430 R15: ffffffffa05a82aa
[   10.753146] FS:  00007f8ebb9e5b80(0000) GS:ffff88827fdc0000(0000) knlGS:0000000000000000
[   10.753146] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   10.753147] CR2: 0000000001e80b08 CR3: 0000000275038006 CR4: 0000000000360ee0
[   10.753149] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[   10.753149] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[   10.753149] Call Trace:
[   10.753189]  ? rtw_chbw_to_freq_range+0x3b/0xb0 [8821cu]
[   10.753210]  ? rtw_is_dfs_ch+0x2f/0x6b [8821cu]
[   10.753235]  ? rtw_regd_apply_flags+0xc8/0xd9 [8821cu]
[   10.753260]  rtw_wiphy_register+0x25/0x4f [8821cu]
[   10.753290]  rtw_cfg80211_ndev_res_register+0x10/0x51 [8821cu]
[   10.753319]  rtw_os_ndev_register+0x107/0x181 [8821cu]
[   10.753343]  rtw_os_ndevs_register+0x95/0x119 [8821cu]
[   10.753367]  rtw_os_ndevs_init+0x1f/0x33 [8821cu]
[   10.753391]  rtw_drv_init+0x4b8/0x5dd [8821cu]
[   10.753393]  usb_probe_interface+0xdf/0x230
[   10.753399]  really_probe+0xe6/0x280
[   10.753400]  driver_probe_device+0x4b/0x90
[   10.753401]  device_driver_attach+0x4e/0x60
[   10.753402]  __driver_attach+0x47/0xb0
[   10.753403]  ? device_driver_attach+0x60/0x60
[   10.753404]  bus_for_each_dev+0x73/0xb0
[   10.753406]  bus_add_driver+0x167/0x1b0
[   10.753407]  driver_register+0x67/0xb0
[   10.753409]  usb_register_driver+0x71/0x110
[   10.753409]  ? 0xffffffffa0369000
[   10.753423]  rtw_drv_entry+0xbb/0x1000 [8821cu]
[   10.753450]  do_one_initcall+0x47/0x17f
[   10.753453]  ? kmem_cache_alloc+0xd0/0x170
[   10.753455]  do_init_module+0x51/0x200
[   10.753456]  load_module+0x23c5/0x24f0
[   10.753457]  ? asymmetric_verify+0xa1/0x1e0
[   10.753459]  ? __do_sys_finit_module+0xbf/0xe0
[   10.753460]  __do_sys_finit_module+0xbf/0xe0
[   10.753461]  do_syscall_64+0x5a/0x1c0
[   10.753462]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[   10.753463] RIP: 0033:0x7f8ebbaddb4d
[   10.753465] Code: 00 c3 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 13 93 0c 00 f7 d8 64 89 01 48
[   10.753465] RSP: 002b:00007ffcaa5e88b8 EFLAGS: 00000206 ORIG_RAX: 0000000000000139
[   10.753466] RAX: ffffffffffffffda RBX: 00000000013f1ae0 RCX: 00007f8ebbaddb4d
[   10.753466] RDX: 0000000000000000 RSI: 000000000041b090 RDI: 0000000000000003
[   10.753467] RBP: 000000000041b090 R08: 0000000000000000 R09: 0000000000000000
[   10.753467] R10: 0000000000000003 R11: 0000000000000206 R12: 0000000000000000
[   10.753468] R13: 00000000013f2210 R14: 0000000000040000 R15: 00000000013f1ae0
[   10.753468] ---[ end trace ab43c952f683a7e2 ]---
[   10.753469] ------------[ cut here ]------------
[   10.753508] WARNING: CPU: 7 PID: 5732 at /root/rtl8821CU/os_dep/linux/os_intfs.c:1647 rtw_os_ndev_register+0xac/0x181 [8821cu]
[   10.753508] Modules linked in: pcc_cpufreq(-) acpi_cpufreq(-) xt_multiport ip6t_rpfilter ip6t_REJECT nf_reject_ipv6 ipt_REJECT nf_reject_ipv4 xt_conntrack ebtable_nat ip6table_nat ip6table_mangle ip6table_security ip6table_raw iptable_nat nf_nat iptable_mangle iptable_security iptable_raw nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 8821cu(OE+) ebtable_filter ebtables intel_rapl_msr intel_rapl_common ip6table_filter ip6_tables iptable_filter bpfilter crct10dif_pclmul crc32_pclmul crc32c_intel snd_pcm_oss ghash_clmulni_intel snd_mixer_oss iTCO_wdt aesni_intel iTCO_vendor_support bochs_drm aes_x86_64 uhci_hcd snd_hda_intel crypto_simd drm_vram_helper snd_hda_codec cryptd ttm glue_helper snd_hda_core joydev drm_kms_helper snd_hwdep snd_pcm drm intel_agp snd_timer intel_gtt snd lpc_ich soundcore ehci_pci agpgart ehci_hcd serio_raw i2c_i801 evdev sch_fq_codel ip_tables
[   10.753518] CPU: 7 PID: 5732 Comm: modprobe Tainted: G        W  OE     5.3.1 #1
[   10.753518] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS rel-1.12.1-0-ga5cab58e9a3f-prebuilt.qemu.org 04/01/2014
[   10.753542] RIP: 0010:rtw_os_ndev_register+0xac/0x181 [8821cu]
[   10.753543] Code: 4d 39 fd 0f 85 a4 00 00 00 48 89 ef e8 4e 60 e6 e1 85 c0 0f 94 c0 0f b6 c0 e9 9f 00 00 00 48 c7 c7 40 dd 5b a0 e8 9e c2 bf e0 <0f> 0b e9 b6 00 00 00 c6 83 60 45 00 00 01 e9 b7 00 00 00 0f b6 8b
[   10.753543] RSP: 0018:ffff888273e07a50 EFLAGS: 00010246
[   10.753544] RAX: 0000000000000024 RBX: ffffc900000f9000 RCX: 0000000000000006
[   10.753544] RDX: 0000000000000000 RSI: 0000000000000086 RDI: ffff88827fdd73d0
[   10.753545] RBP: ffff888274d2f000 R08: 0000000000000462 R09: 0000000000000001
[   10.753545] R10: 0000000000000000 R11: 0000000000000001 R12: ffffc900000fc38e
[   10.753545] R13: 0000000000000000 R14: ffffc900000fc430 R15: ffffffffa05a82aa
[   10.753546] FS:  00007f8ebb9e5b80(0000) GS:ffff88827fdc0000(0000) knlGS:0000000000000000
[   10.753547] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   10.753547] CR2: 0000000001e80b08 CR3: 0000000275038006 CR4: 0000000000360ee0
[   10.753549] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[   10.753549] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[   10.753549] Call Trace:
[   10.753573]  rtw_os_ndevs_register+0x95/0x119 [8821cu]
[   10.753595]  rtw_os_ndevs_init+0x1f/0x33 [8821cu]
[   10.753618]  rtw_drv_init+0x4b8/0x5dd [8821cu]
[   10.753620]  usb_probe_interface+0xdf/0x230
[   10.753621]  really_probe+0xe6/0x280
[   10.753623]  driver_probe_device+0x4b/0x90
[   10.753624]  device_driver_attach+0x4e/0x60
[   10.753625]  __driver_attach+0x47/0xb0
[   10.753626]  ? device_driver_attach+0x60/0x60
[   10.753627]  bus_for_each_dev+0x73/0xb0
[   10.753628]  bus_add_driver+0x167/0x1b0
[   10.753629]  driver_register+0x67/0xb0
[   10.753630]  usb_register_driver+0x71/0x110
[   10.753631]  ? 0xffffffffa0369000
[   10.753644]  rtw_drv_entry+0xbb/0x1000 [8821cu]
[   10.753645]  do_one_initcall+0x47/0x17f
[   10.753646]  ? kmem_cache_alloc+0xd0/0x170
[   10.753647]  do_init_module+0x51/0x200
[   10.753648]  load_module+0x23c5/0x24f0
[   10.753649]  ? asymmetric_verify+0xa1/0x1e0
[   10.753650]  ? __do_sys_finit_module+0xbf/0xe0
[   10.753651]  __do_sys_finit_module+0xbf/0xe0
[   10.753652]  do_syscall_64+0x5a/0x1c0
[   10.753653]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[   10.753654] RIP: 0033:0x7f8ebbaddb4d
[   10.753655] Code: 00 c3 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 13 93 0c 00 f7 d8 64 89 01 48
[   10.753655] RSP: 002b:00007ffcaa5e88b8 EFLAGS: 00000206 ORIG_RAX: 0000000000000139
[   10.753656] RAX: ffffffffffffffda RBX: 00000000013f1ae0 RCX: 00007f8ebbaddb4d
[   10.753656] RDX: 0000000000000000 RSI: 000000000041b090 RDI: 0000000000000003
[   10.753657] RBP: 000000000041b090 R08: 0000000000000000 R09: 0000000000000000
[   10.753657] R10: 0000000000000003 R11: 0000000000000206 R12: 0000000000000000
[   10.753657] R13: 00000000013f2210 R14: 0000000000040000 R15: 00000000013f1ae0
[   10.753658] ---[ end trace ab43c952f683a7e3 ]---
[   10.806168] ------------[ cut here ]------------
[   10.806261] WARNING: CPU: 7 PID: 5732 at /root/rtl8821CU/os_dep/linux/os_intfs.c:3105 rtw_os_ndevs_register+0xef/0x119 [8821cu]
[   10.806262] Modules linked in: acpi_cpufreq(-) xt_multiport ip6t_rpfilter ip6t_REJECT nf_reject_ipv6 ipt_REJECT nf_reject_ipv4 xt_conntrack ebtable_nat ip6table_nat ip6table_mangle ip6table_security ip6table_raw iptable_nat nf_nat iptable_mangle iptable_security iptable_raw nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 8821cu(OE+) ebtable_filter ebtables intel_rapl_msr intel_rapl_common ip6table_filter ip6_tables iptable_filter bpfilter crct10dif_pclmul crc32_pclmul crc32c_intel snd_pcm_oss ghash_clmulni_intel snd_mixer_oss iTCO_wdt aesni_intel iTCO_vendor_support bochs_drm aes_x86_64 uhci_hcd snd_hda_intel crypto_simd drm_vram_helper snd_hda_codec cryptd ttm glue_helper snd_hda_core joydev drm_kms_helper snd_hwdep snd_pcm drm intel_agp snd_timer intel_gtt snd lpc_ich soundcore ehci_pci agpgart ehci_hcd serio_raw i2c_i801 evdev sch_fq_codel ip_tables
[   10.806278] CPU: 7 PID: 5732 Comm: modprobe Tainted: G        W  OE     5.3.1 #1
[   10.806278] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS rel-1.12.1-0-ga5cab58e9a3f-prebuilt.qemu.org 04/01/2014
[   10.806304] RIP: 0010:rtw_os_ndevs_register+0xef/0x119 [8821cu]
[   10.806305] Code: 59 a0 48 c7 c7 90 dd 5b a0 e8 2c b5 bf e0 48 c7 c7 40 dd 5b a0 e8 20 b5 bf e0 0f 0b eb ba 48 c7 c7 40 dd 5b a0 e8 10 b5 bf e0 <0f> 0b 85 ed 74 0d 48 89 df e8 f2 cf 01 00 e9 2b ff ff ff 48 63 ed
[   10.806306] RSP: 0018:ffff888273e07a88 EFLAGS: 00010246
[   10.806306] RAX: 0000000000000024 RBX: ffff888274d2a000 RCX: 0000000000000000
[   10.806307] RDX: 0000000000000000 RSI: ffff88827fdd73d8 RDI: ffff88827fdd73d8
[   10.806307] RBP: 0000000000000000 R08: ffff88827fdd73d8 R09: 0000000000000001
[   10.806307] R10: 0000000000000000 R11: 0000000000000001 R12: 0000000000000001
[   10.806308] R13: 0000000000000000 R14: ffffc900000f9000 R15: ffffffffa05a82aa
[   10.806309] FS:  00007f8ebb9e5b80(0000) GS:ffff88827fdc0000(0000) knlGS:0000000000000000
[   10.806309] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   10.806310] CR2: 0000000001e80b08 CR3: 0000000275038006 CR4: 0000000000360ee0
[   10.806312] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[   10.806312] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[   10.806313] Call Trace:
[   10.806339]  rtw_os_ndevs_init+0x1f/0x33 [8821cu]
[   10.806364]  rtw_drv_init+0x4b8/0x5dd [8821cu]
[   10.806368]  usb_probe_interface+0xdf/0x230
[   10.806370]  really_probe+0xe6/0x280
[   10.806371]  driver_probe_device+0x4b/0x90
[   10.806373]  device_driver_attach+0x4e/0x60
[   10.806374]  __driver_attach+0x47/0xb0
[   10.806375]  ? device_driver_attach+0x60/0x60
[   10.806376]  bus_for_each_dev+0x73/0xb0
[   10.806377]  bus_add_driver+0x167/0x1b0
[   10.806378]  driver_register+0x67/0xb0
[   10.806380]  usb_register_driver+0x71/0x110
[   10.806381]  ? 0xffffffffa0369000
[   10.806394]  rtw_drv_entry+0xbb/0x1000 [8821cu]
[   10.806396]  do_one_initcall+0x47/0x17f
[   10.806398]  ? kmem_cache_alloc+0xd0/0x170
[   10.806399]  do_init_module+0x51/0x200
[   10.806400]  load_module+0x23c5/0x24f0
[   10.806402]  ? asymmetric_verify+0xa1/0x1e0
[   10.806404]  ? __do_sys_finit_module+0xbf/0xe0
[   10.806404]  __do_sys_finit_module+0xbf/0xe0
[   10.806406]  do_syscall_64+0x5a/0x1c0
[   10.806407]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[   10.806408] RIP: 0033:0x7f8ebbaddb4d
[   10.806409] Code: 00 c3 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 13 93 0c 00 f7 d8 64 89 01 48
[   10.806410] RSP: 002b:00007ffcaa5e88b8 EFLAGS: 00000206 ORIG_RAX: 0000000000000139
[   10.806410] RAX: ffffffffffffffda RBX: 00000000013f1ae0 RCX: 00007f8ebbaddb4d
[   10.806411] RDX: 0000000000000000 RSI: 000000000041b090 RDI: 0000000000000003
[   10.806411] RBP: 000000000041b090 R08: 0000000000000000 R09: 0000000000000000
[   10.806412] R10: 0000000000000003 R11: 0000000000000206 R12: 0000000000000000
[   10.806412] R13: 00000000013f2210 R14: 0000000000040000 R15: 00000000013f1ae0
[   10.806413] ---[ end trace ab43c952f683a7e4 ]---
[   10.809475] RTW: WARN free_recv_skb_queue not empty, 8

**Comment by smp79** [comment]
[Fix for kernel 5.3](https://github.com/smp79/rtl8821CU/commit/2ec29cfa7fd05d2321aa022c8281b97c1d190665). Tested and working.

**Comment by breisig** [comment]
Can we get this merged?

**Comment by troyfolger** [comment]
+1 for merging this -- I tested on Fedora 30 with 5.3.5-200.fc30.x86_64 and it works ...

**Comment by rrafal1337** [comment]
Same for me, tested on 5.3.6 - Fedora 30:
https://pastebin.com/2r07xtXT
![obraz](https://user-images.githubusercontent.com/47420388/67280237-00c69c80-f4cd-11e9-983e-e40858ca74a2.png)

I don't see new commit for branch master. Do fix exists in some other branch?

**Comment by brektrou** [comment]
Fixed: 23c0a81b5795bd6d794c13fbeb76509cef6ad76e db47217e31b95b4a760a58d6c4790631d1da4896
