### ISSUE TITLE
Why do we need to check the interface name?

### ISSUE THREAD

**Issue by eyalroz** [brektrou/rtl8821CU#162]
The installation instructions in the README require us to determine the name of the wifi adapter interface. 

1. Why?
2. How would we have this name before the driver is already installed and working?

**Comment by multikirin** [comment]
I dont see that, where is it?

**Comment by eyalroz** [comment]
@multikirin : It's right there in the README file...

> ### Check the name of the interface

**Comment by multikirin** [comment]
If you arent using a obscure distro, skip that stepOn 20/03/22, 21:41 Eyal Rozenberg ***@***.***> wrote:

   
  @multikirin : It's right there in the README file... 
   
   Check the name of the interface

**Comment by eyalroz** [comment]
> If you arent using a obscure distro, skip that step

I see. Please consider clarifying this in the README itself, so that other people don't get confused and try to do something with the interface name even if they don't need to.

Otherwise - thank you so much for writing this driver!
