### ISSUE TITLE
does this driver support rtl8811cu on openwrt?

### ISSUE THREAD

**Issue by youkechat** [brektrou/rtl8821CU#171]
I use this driver compiled for openwrt 21.02, it can identify wifi card, but enable wifi will made all network down, can support openwrt arm8?

**Comment by youkechat** [comment]
I notice network down only if after install wpad/hostapd, but still cannnot work, two problem:
1. just 802.11bg, not 802.11ac，though this chip support 802.11ac
2. I have tried all channel, but none work, my openwrt config error? or driver error? it seems driver problem, for if I install hostapd, entire network cannot work, include lan

**Comment by Quanff** [comment]
I use this driver in openwrt 18.06，it can open the wifi ap, but the wifi speed is too low, the iperf test  UDP only 5Mbps. Should i modify the code in order to get high speed ,but i don't know how to modify
