### ISSUE TITLE
About p2p function,  The third party device could not find the name of the 8821cu P2P

### ISSUE THREAD

**Issue by renhongwei** [brektrou/rtl8821CU#24]
I enable p2p function of the 8821cu. 
The surrounding device can be found through the p2p_find command, However, when searching for 8821cu through other devices, This device cannot be found in other devices.
Thanks.

**Comment by renhongwei** [comment]
It's been solved.
Root cause: p2p_listen_state_process

**Comment by mystery-nobody** [comment]
I've had the same problem. How did you solve it?
