### ISSUE TITLE
Missing bluetooth

### ISSUE THREAD

**Issue by DraTrav** [brektrou/rtl8821CU#36]
The wifi part works but no bluetooth adapter is detected even though the chip supports bluetooth

**Comment by etem** [comment]
Same issue here on Fedora 30 kernel 5.4.18

**Comment by etem** [comment]
I've managed to fix that following [this](https://fedoraproject.org/wiki/How_to_debug_Bluetooth_problems) guide for Fedora.

Basically following sequence of commands needs to be applied
- `usb_modeswitch -KW -v 0bda -p 1a2b` - switching adapter mode from USB storage to network adapter
- `systemctl start bluetooth.service` - starting Bluetooth service
- `hciconfig up` - enabling Bluetooth device if it's in down state

**Comment by etem** [comment]
Btw, I'm using version 5.4.1 of the driver.

**Comment by DraTrav** [comment]
Perfect! that worked, wish it was in the main guide
