### ISSUE TITLE
Error on Kali 2020.1

### ISSUE THREAD

**Issue by zabeiua** [brektrou/rtl8821CU#40]
make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.4.0-kali3-amd64/build M=/home/i/build/rtl8821CU  modules
make[1]: *** /lib/modules/5.4.0-kali3-amd64/build: No such file or directory.  Stop.
make: *** [Makefile:2183: modules] Error 2

**Comment by SatanicRaw** [comment]
Install linux-headers

**Comment by zabeiua** [comment]
It woks now!
