### ISSUE TITLE
raspberry pi 4 build error

### ISSUE THREAD

**Issue by CMCCAdmin** [brektrou/rtl8821CU#47]
make ARCH=arm CROSS_COMPILE= -C /lib/modules/4.19.97-v7l+/build M=/home/pi/rtl8821CU  modules
make[1]: 进入目录“/usr/src/linux-headers-4.19.97-v7l+”
  CC [M]  /home/pi/rtl8821CU/core/rtw_cmd.o
gcc: error: -mfloat-abi=soft and -mfloat-abi=hard may not be used together
make[2]: *** [scripts/Makefile.build:304：/home/pi/rtl8821CU/core/rtw_cmd.o] 错误 1
make[1]: *** [Makefile:1522：_module_/home/pi/rtl8821CU] 错误 2
make[1]: 离开目录“/usr/src/linux-headers-4.19.97-v7l+”
make: *** [Makefile:2213：modules] 错误 2

**Comment by rrafal1337** [comment]
Hi. You need to follow this instruction to avoid this problem: https://github.com/brektrou/rtl8821CU#arm-architecture-tweak-for-this-driver-this-solves-compilation-problem-of-this-driver
By default is -mfloat-abi=soft but this driver requires -mfloat-abi=hard and you can't use both at same time.
