### ISSUE TITLE
Cannot set monitor mode

### ISSUE THREAD

**Issue by breisig** [brektrou/rtl8821CU#6]
I cannot seem to set the wireless access into monitor mode? I have a 

Bus 001 Device 002: ID 0bda:c811 Realtek Semiconductor Corp. 802.11ac NIC

device and when trying to set up monitor mode using the following,

systemctl stop NetworkManager
airmon-ng check kill
ip link set wlan0 down
iw dev wlan0 set type monitor

I get the error message
command failed: Operation not supported (-95)

**Comment by brektrou** [comment]
Open `Makefile`. Go to this line:
`CONFIG_WIFI_MONITOR = n`
Change to:
`CONFIG_WIFI_MONITOR = y`

Recompile the driver
Monitor mode is disable by default in `Makefile`

**Comment by breisig** [comment]
Thanks @brektrou , that worked!
