### ISSUE TITLE
modprobe: FATAL: Module 8821cu not found in directory /lib/modules/5.8.7-200.fc32.x86_64

### ISSUE THREAD

**Issue by leonevilred** [brektrou/rtl8821CU#84]
please help me!thank you !
modprobe: FATAL: Module 8821cu not found in directory /lib/modules/5.8.7-200.fc32.x86_64
distro:fedora workstation 32

[root@localhost rtl8821CU]# ./dkms-install.sh 
About to run dkms install steps...
Error! DKMS tree already contains: rtl8821CU-5.4.1
You cannot add the same module/version combo more than once.
Error! echo
Your kernel headers for kernel 5.8.7-200.fc32.x86_64 cannot be found at
/lib/modules/5.8.7-200.fc32.x86_64/build or /lib/modules/5.8.7-200.fc32.x86_64/source.
You can use the --kernelsourcedir option to tell DKMS where it's located.
Error! echo
Your kernel headers for kernel 5.8.7-200.fc32.x86_64 cannot be found at
/lib/modules/5.8.7-200.fc32.x86_64/build or /lib/modules/5.8.7-200.fc32.x86_64/source.
You can use the --kernelsourcedir option to tell DKMS where it's located.
Finished running dkms install steps.

**Comment by brektrou** [comment]
To install the driver, you need to install kernel headers
`sudo dnf install kernel-headers`
